import { AlertTriangle, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

export function NeedsReviewBadge({ className }: { className?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full border border-warn/30 bg-warn-soft px-2 py-0.5 text-xs font-medium text-warn",
        className,
      )}
    >
      <AlertTriangle className="size-3" aria-hidden />
      Needs review
    </span>
  );
}

/** Marks every AI-generated element. */
export function AiBadge({ className, label = "AI" }: { className?: string; label?: string }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-0.5 rounded-md border border-cobalt/25 bg-cobalt-soft px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-cobalt",
        className,
      )}
      title="Generated by AI — reviewed by a person"
    >
      <Sparkles className="size-2.5" aria-hidden />
      {label}
    </span>
  );
}

const TONES = {
  ok: "border-ok/25 bg-ok-soft text-ok",
  warn: "border-warn/30 bg-warn-soft text-warn",
  bad: "border-bad/30 bg-bad-soft text-bad",
  neutral: "border-border bg-muted text-muted-foreground",
  cobalt: "border-cobalt/25 bg-cobalt-soft text-cobalt",
} as const;

export function StatusPill({ tone, children, className }: { tone: keyof typeof TONES; children: React.ReactNode; className?: string }) {
  return (
    <span className={cn("inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs font-medium", TONES[tone], className)}>
      {children}
    </span>
  );
}
