/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/supplier/workers/{workerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateWorker"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/timesheets/{timesheetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateTimesheet"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/workers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workers"];
        put?: never;
        post: operations["createWorker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/orders/{missionId}/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["propose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/invoices/{invoiceId}/credit-note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["creditNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/contracts/{contractId}/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/timesheets/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["check"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/timesheets/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/sourcing/select/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["select"];
        delete: operations["unselect"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/sourcing/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/phases/{phase}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finalizePhase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/invoice/request-credit-note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestCreditNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/invoice/receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["receive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/invoice/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/intake/fields/{field}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/intake/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["extract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/contracts/sign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sign_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/contracts/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/extract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["extract_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intake/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["preview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contracts/{contractId}/fix/{ruleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["demoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/anomalies/{anomalyId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/evals/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recordRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/demo/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["suppliers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["supplier"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/orders/{missionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["order"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/orders/{missionId}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["order_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["invoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/request-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["templates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/timesheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/sourcing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missions/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoiceId}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["pdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["personas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/usage/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/usage/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metrics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metrics/evals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["evals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/supplier/orders/{missionId}/proposals/{candidateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorkerForm: {
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            city?: string;
            skills?: string[];
            certifications?: string[];
            /** Format: int32 */
            experienceYears?: number;
            /** Format: date */
            availableFrom?: string;
            /** Format: date */
            availableTo?: string;
            profile?: string;
        };
        WorkerView: {
            /** Format: int64 */
            id: number;
            firstName: string;
            lastName: string;
            email: string;
            phone: string;
            city: string;
            skills: string[];
            certifications: string[];
            /** Format: int32 */
            experienceYears: number;
            /** Format: date */
            availableFrom: string;
            /** Format: date */
            availableTo: string;
            profile: string;
            /** Format: int32 */
            activePlacements: number;
            /** Format: date */
            placedUntil: string;
        };
        TimesheetUpdate: {
            dailyHours?: number[];
        };
        TimesheetView: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            contractId: number;
            contractRef: string;
            /** Format: int64 */
            workerId: number;
            workerName: string;
            supplierName: string;
            /** Format: date */
            weekStart: string;
            dailyHours: number[];
            total: number;
            contractedHours: number;
            status: string;
            approvedHours: number;
            flaggedDays: number[];
        };
        ProposeRequest: {
            /** Format: int64 */
            workerId?: number;
        };
        AnomalyView: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            timesheetId: number;
            workerName: string;
            /** Format: date */
            weekStart: string;
            ruleId: string;
            message: string;
            expectedHours: number;
            actualHours: number;
            flaggedDays: number[];
            aiExplanation: string;
            status: string;
            /** @enum {string} */
            resolution: "APPROVE_OVERTIME" | "RETURN_TO_SUPPLIER";
            /** Format: date-time */
            resolvedAt: string;
        };
        CandidateView: {
            /** Format: int64 */
            candidateId: number;
            /** Format: int64 */
            workerId: number;
            workerName: string;
            supplierName: string;
            city: string;
            /** Format: int32 */
            rank: number;
            /** Format: double */
            score: number;
            /** Format: double */
            similarity: number;
            /** Format: double */
            distanceKm: number;
            /** Format: int32 */
            experienceYears: number;
            certifications: string[];
            skills: string[];
            eligible: boolean;
            exclusionReasons: string[];
            explanation: components["schemas"]["Item"][];
            aiSummary: string;
            selected: boolean;
        };
        ContractView: {
            /** Format: int64 */
            id: number;
            ref: string;
            workerName: string;
            supplierName: string;
            position: string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            hourlyRate: number;
            weeklyHours: number;
            overtimeAllowed: boolean;
            legalReason: string;
            replacedEmployee: string;
            attachedCertificates: string[];
            content: string;
            aiDrafted: boolean;
            status: string;
            /** Format: date-time */
            signedByClientAt: string;
            /** Format: date-time */
            signedBySupplierAt: string;
            checks: components["schemas"]["RuleResult"][];
            blocking: boolean;
        };
        InvoiceLines: {
            invoiceNumber: string;
            supplierName: string;
            lines: components["schemas"]["Line"][];
            totalExclTax: number;
        };
        InvoiceView: {
            /** Format: int64 */
            id: number;
            ref: string;
            supplierName: string;
            status: string;
            extraction: components["schemas"]["InvoiceLines"];
            aiExtracted: boolean;
            match: components["schemas"]["Result"];
            aiMessageDraft: string;
            creditNoteRef: string;
            creditNoteAmount: number;
            creditNote: {
                [key: string]: unknown;
            };
            extractedText: string;
        };
        Item: {
            ok: boolean;
            text: string;
        };
        Line: {
            workerName: string;
            hours: number;
            hourlyRate: number;
            amount: number;
        };
        LineResult: {
            workerName: string;
            /** @enum {string} */
            status: "MATCH" | "HOURS_MISMATCH" | "RATE_MISMATCH" | "AMOUNT_MISMATCH" | "UNKNOWN_WORKER" | "MISSING_LINE";
            expectedHours: number;
            invoicedHours: number;
            expectedRate: number;
            invoicedRate: number;
            expectedAmount: number;
            invoicedAmount: number;
            delta: number;
            message: string;
        };
        OrderSummary: {
            /** Format: int64 */
            missionId: number;
            ref: string;
            client: string;
            title: string;
            site: string;
            /** @enum {string} */
            phase: "INTAKE" | "SOURCING" | "CONTRACTS" | "TIMESHEETS" | "INVOICE" | "CLOSED";
            position: string;
            /** Format: int32 */
            quantity: number;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: string;
            /** Format: int32 */
            myProposals: number;
            /** Format: int32 */
            myPlacements: number;
        };
        PlacementView: {
            /** Format: int64 */
            workerId: number;
            workerName: string;
            /** Format: date */
            start: string;
            /** Format: date */
            end: string;
        };
        Result: {
            lines: components["schemas"]["LineResult"][];
            expectedTotal: number;
            invoicedTotal: number;
            overbilled: number;
        };
        RuleResult: {
            ruleId: string;
            label: string;
            passed: boolean;
            blocking: boolean;
            autoFixable: boolean;
            message: string;
        };
        Terms: {
            position: string;
            /** Format: int32 */
            quantity: number;
            site: string;
            startDate: string;
            endDate: string;
            schedule: string;
            weeklyHours: number;
            hourlyRate: number;
            legalReason: string;
            requiredCertifications: string[];
            overtimeAllowed: boolean;
        };
        Workspace: {
            order: components["schemas"]["OrderSummary"];
            terms: components["schemas"]["Terms"];
            canPropose: boolean;
            canSignContracts: boolean;
            canEditTimesheets: boolean;
            canIssueCreditNotes: boolean;
            proposals: components["schemas"]["CandidateView"][];
            placements: components["schemas"]["PlacementView"][];
            contracts: components["schemas"]["ContractView"][];
            timesheets: components["schemas"]["TimesheetView"][];
            anomalies: components["schemas"]["AnomalyView"][];
            invoices: components["schemas"]["InvoiceView"][];
        };
        CreateMissionRequest: {
            templateCode?: string;
            emailText?: string;
            title?: string;
        };
        ArtifactView: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            phase: "INTAKE" | "SOURCING" | "CONTRACTS" | "TIMESHEETS" | "INVOICE" | "CLOSED";
            type: string;
            ref: string;
            status: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            updatedAt: string;
        };
        GateCheck: {
            id: string;
            label: string;
            passed: boolean;
            action: string;
            needsReview: boolean;
        };
        GateView: {
            /** @enum {string} */
            phase: "INTAKE" | "SOURCING" | "CONTRACTS" | "TIMESHEETS" | "INVOICE" | "CLOSED";
            checks: components["schemas"]["GateCheck"][];
            ready: boolean;
        };
        MissionDetail: {
            /** Format: int64 */
            id: number;
            ref: string;
            title: string;
            site: string;
            /** @enum {string} */
            phase: "INTAKE" | "SOURCING" | "CONTRACTS" | "TIMESHEETS" | "INVOICE" | "CLOSED";
            closed: boolean;
            needsReview: boolean;
            nextAction: string;
            gate: components["schemas"]["GateView"];
            phases: components["schemas"]["PhaseStep"][];
            artifacts: components["schemas"]["ArtifactView"][];
            positions: components["schemas"]["PositionsView"];
            sourceEmail: string;
            templateCode: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            closedAt: string;
            summary: {
                [key: string]: unknown;
            };
        };
        PhaseStep: {
            /** @enum {string} */
            phase: "INTAKE" | "SOURCING" | "CONTRACTS" | "TIMESHEETS" | "INVOICE" | "CLOSED";
            label: string;
            /** @enum {string} */
            state: "DONE" | "ACTIVE" | "LOCKED";
            /** Format: date-time */
            finalizedAt: string;
            finalizedBy: string;
        };
        PositionsView: {
            /** Format: int32 */
            filled: number;
            /** Format: int32 */
            total: number;
        };
        TimesheetsView: {
            /** Format: int64 */
            missionId: number;
            readOnly: boolean;
            checked: boolean;
            /** Format: date-time */
            checkedAt: string;
            approved: boolean;
            timesheets: components["schemas"]["TimesheetView"][];
            anomalies: components["schemas"]["AnomalyView"][];
            totals: components["schemas"]["WorkerHours"][];
        };
        WorkerHours: {
            /** Format: int64 */
            workerId: number;
            workerName: string;
            submitted: number;
            approved: number;
        };
        SourcingView: {
            /** Format: int64 */
            missionId: number;
            published: boolean;
            /** Format: date-time */
            publishedAt: string;
            suppliers: string[];
            /** Format: int32 */
            quantity: number;
            /** Format: int32 */
            filled: number;
            readOnly: boolean;
            candidates: components["schemas"]["CandidateView"][];
            excluded: components["schemas"]["CandidateView"][];
        };
        InvoicesView: {
            /** Format: int64 */
            missionId: number;
            received: boolean;
            readOnly: boolean;
            invoices: components["schemas"]["InvoiceView"][];
            expectedTotal: number;
            invoicedTotal: number;
            creditNotes: number;
        };
        ConfirmRequest: {
            value?: string;
        };
        FieldView: {
            name: string;
            label: string;
            value: string;
            aiValue: string;
            /** Format: double */
            confidence: number;
            errors: string[];
            needsReview: boolean;
            confirmed: boolean;
            corrected: boolean;
        };
        IntakeView: {
            /** Format: int64 */
            missionId: number;
            emailText: string;
            extracted: boolean;
            /** Format: date-time */
            extractedAt: string;
            readOnly: boolean;
            /** Format: int32 */
            needsReviewCount: number;
            /** Format: double */
            confidenceThreshold: number;
            fields: components["schemas"]["FieldView"][];
        };
        ContractsView: {
            /** Format: int64 */
            missionId: number;
            generated: boolean;
            readOnly: boolean;
            /** Format: int32 */
            placements: number;
            contracts: components["schemas"]["ContractView"][];
        };
        ExtractRequest: {
            text?: string;
        };
        PreviewRequest: {
            emailText?: string;
        };
        PreviewView: {
            fields: components["schemas"]["FieldView"][];
            model: string;
            /** Format: int64 */
            latencyMs: number;
        };
        DocumentView: {
            /** Format: int64 */
            id: number;
            title: string;
            source: string;
            contentType: string;
            /** Format: int32 */
            chunks: number;
            /** Format: date-time */
            createdAt: string;
        };
        AskRequest: {
            question?: string;
        };
        Citation: {
            /** Format: int32 */
            n: number;
            /** Format: int64 */
            documentId: number;
            documentTitle: string;
            heading: string;
            excerpt: string;
        };
        CopilotAnswer: {
            question: string;
            answer: string;
            notFound: boolean;
            citations: components["schemas"]["Citation"][];
            sources: components["schemas"]["Citation"][];
            toolCalls: components["schemas"]["ToolCallView"][];
            model: string;
            /** Format: int64 */
            latencyMs: number;
        };
        ToolCallView: {
            name: string;
            arguments: unknown;
            result: unknown;
        };
        DemoLoginRequest: {
            persona: string;
        };
        Me: {
            /** Format: int64 */
            userId: number;
            persona: string;
            displayName: string;
            jobTitle: string;
            /** @enum {string} */
            role: "BUYER" | "SUPPLIER" | "ADMIN";
            tenant: components["schemas"]["NamedRef"];
            supplier: components["schemas"]["NamedRef"];
        };
        NamedRef: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        ResolveRequest: {
            /** @enum {string} */
            resolution?: "APPROVE_OVERTIME" | "RETURN_TO_SUPPLIER";
        };
        EvalRunRequest: {
            gitSha?: string;
            profile?: string;
            passed?: boolean;
            metrics?: {
                [key: string]: unknown;
            };
            thresholds?: {
                [key: string]: unknown;
            };
        };
        EvalRun: {
            /** Format: int64 */
            id: number;
            gitSha: string;
            profile: string;
            passed: boolean;
            metrics: {
                [key: string]: unknown;
            };
            thresholds: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        ResetResult: {
            /** Format: int32 */
            missions: number;
        };
        TenantView: {
            /** Format: int64 */
            id: number;
            code: string;
            name: string;
            sector: string;
        };
        SupplierView: {
            /** Format: int64 */
            id: number;
            code: string;
            name: string;
        };
        PoolView: {
            workers: components["schemas"]["WorkerView"][];
            cities: string[];
        };
        OrderDetail: {
            order: components["schemas"]["OrderSummary"];
            myProposals: components["schemas"]["CandidateView"][];
            myPlacements: components["schemas"]["PlacementView"][];
        };
        SupplierInvoice: {
            /** Format: int64 */
            id: number;
            ref: string;
            missionRef: string;
            client: string;
            status: string;
            total: number;
            creditNoteRef: string;
            creditNoteAmount: number;
            payable: number;
        };
        Dashboard: {
            /** Format: int32 */
            openOrders: number;
            /** Format: int32 */
            ordersToStaff: number;
            /** Format: int32 */
            activePlacements: number;
            /** Format: int32 */
            contractsToSign: number;
            /** Format: int32 */
            timesheetsToFix: number;
            /** Format: int32 */
            invoicesToCredit: number;
            /** Format: int32 */
            workers: number;
            todo: components["schemas"]["TodoItem"][];
        };
        TodoItem: {
            /** Format: int64 */
            missionId: number;
            missionRef: string;
            client: string;
            kind: string;
            label: string;
        };
        TemplateView: {
            code: string;
            title: string;
            site: string;
            description: string;
            emailText: string;
        };
        MissionSummary: {
            /** Format: int64 */
            id: number;
            ref: string;
            title: string;
            site: string;
            /** @enum {string} */
            phase: "INTAKE" | "SOURCING" | "CONTRACTS" | "TIMESHEETS" | "INVOICE" | "CLOSED";
            phases: components["schemas"]["PhaseStep"][];
            positions: components["schemas"]["PositionsView"];
            nextAction: string;
            needsReview: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AuditView: {
            /** Format: int64 */
            id: number;
            actorKind: string;
            actorName: string;
            action: string;
            summary: string;
            details: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        Persona: {
            persona: string;
            displayName: string;
            jobTitle: string;
            /** @enum {string} */
            role: "BUYER" | "SUPPLIER" | "ADMIN";
            organization: string;
        };
        ModelPrice: {
            model: string;
            inputPerMillion: number;
            outputPerMillion: number;
        };
        UsageConfig: {
            profile: string;
            chatModel: string;
            embeddingModel: string;
            dailyBudgetUsd: number;
            liveSpendTodayUsd: number;
            /** Format: double */
            budgetUsedToday: number;
            /** Format: int32 */
            rateLimitPerMinute: number;
            /** Format: int32 */
            defaultMaxTokens: number;
            pricing: components["schemas"]["ModelPrice"][];
        };
        UsageOverview: {
            /** Format: int32 */
            days: number;
            config: components["schemas"]["UsageConfig"];
            totals: components["schemas"]["UsageTotals"];
            users: components["schemas"]["UserUsage"][];
        };
        UsageTotals: {
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            okCalls: number;
            /** Format: int64 */
            failedCalls: number;
            /** Format: int64 */
            refusedCalls: number;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            costUsd: number;
            liveCostUsd: number;
            avgDailyCostUsd: number;
            projectedMonthlyCostUsd: number;
            /** Format: int64 */
            activeUsers: number;
        };
        UserUsage: {
            /** Format: int64 */
            userId: number;
            displayName: string;
            persona: string;
            role: string;
            organization: string;
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            okCalls: number;
            /** Format: int64 */
            failedCalls: number;
            /** Format: int64 */
            refusedCalls: number;
            /** Format: int64 */
            retries: number;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            costUsd: number;
            liveCostUsd: number;
            /** Format: int64 */
            avgLatencyMs: number;
            /** Format: int64 */
            p95LatencyMs: number;
            /** Format: date-time */
            lastCallAt: string;
            /** Format: double */
            shareOfCost: number;
        };
        UsageBreakdown: {
            key: string;
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            failedCalls: number;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            costUsd: number;
            /** Format: int64 */
            avgLatencyMs: number;
            /** Format: int64 */
            p95LatencyMs: number;
        };
        UsageCall: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            createdAt: string;
            feature: string;
            kind: string;
            model: string;
            profile: string;
            status: string;
            /** Format: int32 */
            attempt: number;
            /** Format: int32 */
            inputTokens: number;
            /** Format: int32 */
            outputTokens: number;
            /** Format: int64 */
            latencyMs: number;
            costUsd: number;
            missionRef: string;
            error: string;
        };
        UsageDay: {
            /** Format: date */
            day: string;
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            inputTokens: number;
            /** Format: int64 */
            outputTokens: number;
            costUsd: number;
        };
        UsageUserDetail: {
            /** Format: int32 */
            days: number;
            user: components["schemas"]["UserUsage"];
            /** Format: double */
            avgTokensPerCall: number;
            avgCostPerCallUsd: number;
            /** Format: double */
            outputInputRatio: number;
            byFeature: components["schemas"]["UsageBreakdown"][];
            byModel: components["schemas"]["UsageBreakdown"][];
            byStatus: components["schemas"]["UsageBreakdown"][];
            daily: components["schemas"]["UsageDay"][];
            recentCalls: components["schemas"]["UsageCall"][];
        };
        Corrections: {
            /** Format: int64 */
            aiFields: number;
            /** Format: int64 */
            correctedFields: number;
            /** Format: double */
            share: number;
        };
        FeatureRow: {
            feature: string;
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            errors: number;
            /** Format: double */
            errorRate: number;
            /** Format: int64 */
            p50LatencyMs: number;
            /** Format: int64 */
            p95LatencyMs: number;
            /** Format: int64 */
            tokens: number;
            estimatedCostUsd: number;
        };
        Overview: {
            summary: components["schemas"]["Summary"];
            byTenant: components["schemas"]["TenantRow"][];
            byFeature: components["schemas"]["FeatureRow"][];
            corrections: components["schemas"]["Corrections"];
        };
        Summary: {
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            errors: number;
            /** Format: double */
            errorRate: number;
            /** Format: int64 */
            p50LatencyMs: number;
            /** Format: int64 */
            p95LatencyMs: number;
            /** Format: int64 */
            tokens: number;
            estimatedCostUsd: number;
            liveSpendTodayUsd: number;
            dailyBudgetUsd: number;
            profile: string;
        };
        TenantRow: {
            tenant: string;
            /** Format: int64 */
            calls: number;
            /** Format: int64 */
            tokens: number;
            estimatedCostUsd: number;
        };
        AuditRow: {
            /** Format: int64 */
            id: number;
            tenant: string;
            missionRef: string;
            actorKind: string;
            actorName: string;
            action: string;
            summary: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateWorker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workerId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerView"];
                };
            };
        };
    };
    updateTimesheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timesheetId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimesheetUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimesheetView"];
                };
            };
        };
    };
    workers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolView"];
                };
            };
        };
    };
    createWorker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkerForm"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkerView"];
                };
            };
        };
    };
    propose: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                missionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    creditNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoiceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceView"];
                };
            };
        };
    };
    sign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contractId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractView"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMissionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionDetail"];
                };
            };
        };
    };
    check: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimesheetsView"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimesheetsView"];
                };
            };
        };
    };
    select: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                candidateId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcingView"];
                };
            };
        };
    };
    unselect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                candidateId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcingView"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcingView"];
                };
            };
        };
    };
    finalizePhase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                phase: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionDetail"];
                };
            };
        };
    };
    requestCreditNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicesView"];
                };
            };
        };
    };
    receive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicesView"];
                };
            };
        };
    };
    approve_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicesView"];
                };
            };
        };
    };
    confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                field: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeView"];
                };
            };
        };
    };
    extract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeView"];
                };
            };
        };
    };
    sign_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractsView"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractsView"];
                };
            };
        };
    };
    extract_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExtractRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceLines"];
                };
            };
        };
    };
    preview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewView"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"][];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: {
                title?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentView"];
                };
            };
        };
    };
    ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CopilotAnswer"];
                };
            };
        };
    };
    fix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contractId: number;
                ruleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractView"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    demoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                anomalyId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimesheetsView"];
                };
            };
        };
    };
    recordRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"];
                };
            };
        };
    };
    reset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResult"];
                };
            };
        };
    };
    tenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantView"];
                };
            };
        };
    };
    suppliers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierView"][];
                };
            };
        };
    };
    supplier: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierView"];
                };
            };
        };
    };
    orders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderSummary"][];
                };
            };
        };
    };
    order: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                missionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetail"];
                };
            };
        };
    };
    order_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                missionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
    invoices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierInvoice"][];
                };
            };
        };
    };
    dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dashboard"];
                };
            };
        };
    };
    templates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateView"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionDetail"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimesheetsView"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcingView"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicesView"];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeView"];
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractsView"];
                };
            };
        };
    };
    audit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditView"][];
                };
            };
        };
    };
    pdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoiceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
        };
    };
    personas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    users: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageOverview"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: {
                userId?: number;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageUserDetail"];
                };
            };
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
        };
    };
    evals: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRun"][];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                mission?: string;
                actor?: string;
                kind?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditRow"][];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                missionId: number;
                candidateId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
}
